"""Add document_text field to Chat."""
# pylint: disable=invalid-name

# Generated by Django 6.0 on 2026-01-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for adding document_text."""

    dependencies = [
        ('aibot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='document_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
