"""Add Document model."""
# pylint: disable=invalid-name, line-too-long

# Generated by Django 6.0 on 2026-01-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for document model."""

    dependencies = [
        ('aibot', '0002_chat_document_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='aibot.chat')),
            ],
        ),
    ]
